image: archlinux
environment:
  CGO_ENABLED: 1
  POSTGRES_APP_URL: postgres://grokloc:grokloc@localhost:5432/app
  GROKLOC_ENV: UNIT
  REPOSITORY_BASE: /tmp
tasks:
  - update-pacman: |
      sudo pacman -Syu --noconfirm
  - install-pkgs: |
      sudo pacman --noconfirm -S just fish postgresql git go gcc icu
  - grokloc-database: |
      pushd /home/build/grokloc-apiserver/database
      sudo just initdb
      sudo systemctl start postgresql.service && sleep 3
      just create-users create-databases alter-grants apply-schema
      popd
  - tools: |
      cd /home/build/grokloc-apiserver && just tools
  - mod: |
      cd /home/build/grokloc-apiserver && just mod
  - test: |
      cd /home/build/grokloc-apiserver && just test
  - lint: |
      cd /home/build/grokloc-apiserver && export PATH="~/go/bin:$PATH" && golangci-lint --timeout=24h run pkg/... && staticcheck ./... && go vet ./... && govulncheck ./...
